### PR TITLE
Optimize league images

### LINKED ISSUE #65: Optimize league images
Pull is on the way

### PR DESCRIPTION
**Pull request by AmirSavand**
Fixes #65

### CODE REVIEW

**Comment by martincarrera** [comment]
Hey @MaherFa could you take a look at this please? I think it looks good but as you did this work, maybe you have a comment or something. Thanks!

**Comment by MaherFa** [comment]
here I can't see any difference, semi-transparent pixels are part of the shield's shadow designed by SC. needs testing on a bright color background to make sure shadows are intact

**Comment by martincarrera** [comment]
Hey @AmirSavand could you explain a little bit what @MaherFa is asking? Thanks!

**Comment by AmirSavand** [comment]
@MaherFa seems these images do not need tiny crops and may cause problem with the shadows,
So no need to change em.

@martincarrera They already look awesome.

**Comment by martincarrera** [comment]
Ok thanks for your reply, and for your work!

**Pull request closed without merging**
