### PR TITLE
Optimize card images

### LINKED ISSUE #62: Optimize card images
Pull is on the way

### PR DESCRIPTION
**Pull request by AmirSavand**
Fixes #62

### CODE REVIEW

**Comment by AmirSavand** [comment]
Dup

**Comment by AmirSavand** [comment]
Sorry :P

**Comment by martincarrera** [comment]
Hey @MaherFa could you take a look at this please? I think it looks good but as you did this work, maybe you have a comment or something. Thanks!

**Comment by MaherFa** [comment]
@martincarrera I haven't looked at all the images, but I assume it's removing extra pixels for better cropping.

I vote merge as long as they have the same quality and aspect ratio

**Comment by martincarrera** [comment]
Great, thanks!

**Pull request merged**
