### PR TITLE
chest images update

### PR DESCRIPTION
**Pull request by MaherFa**
Updated:
crown-chest
epic-chest
giant-chest
golden-chest
legendary-chest
magical-chest
silver-chest
super-magical-chest
wooden-chest

Added:
clan-chest
draft-chest
classic-challenge-chest
custom-tournament-chest
custom-tournament-winner-chest
grand-challenge-bronze-chest
grand-challenge-silver-chest
grand-challenge-gold-chest

### CODE REVIEW

**Comment by MaherFa** [comment]
My "GitHub Desktop" said fork was identical then went crazy and added e197dba (a revert), I'm still trying to learn my way around, please delete the mentioned commit and tell me if I need to do anything else.

**Comment by amirm3hdi** [comment]
@MaherFa Some images are not perfectly cropped, there's also some darkness around images.

**Comment by MaherFa** [comment]
@amirm3hdi I will improve them later, SC texture files are hell to work with, they re-use tens of parts with different hue and layers. 

if you could list all images with issues here, that would help.

**Comment by amirm3hdi** [comment]
@MaherFa The crop is not that big of deal can be fixed later, but the image I mentioned above is important, left and right side of it has some kinda black area.

**Comment by MaherFa** [comment]
@martincarrera I see this haven't been merged yet, do you wanna delete this pull request and start clean? I can clean edges and improve cropping.

**Comment by amirm3hdi** [comment]
This pull is really good, needs to be merged.

**Comment by martincarrera** [comment]
Hey guys! Sorry for the delay, I think the images are really good, if you want to make an improvement, feel free to submit another pull request. However, I am merging this.

Thanks again for all your amazing work @MaherFa!

**Comment by barreeeiroo** [comment]
WOW, amazing work @MaherFa !!!

**Pull request merged**
