### PR TITLE
Add Deck Royale to the list

### PR DESCRIPTION
**Pull request by ikenami**
I've made a SPA using Vue and Express using this API to generate random decks and display some other information.

You can check the FrontEnd of the app on Deck Royale - https://github.com/ikenami/Deck-Royale.
And you can check the server that runs the app on Deck Royale Server - https://github.com/ikenami/Deck-Royale-Server.
And you can test it on Heroku here - http://deck-royale-ultimate.herokuapp.com/.

### CODE REVIEW

**Comment by TorzuoliH** [comment]
Hey! Seems nice! 😃 
Unfortunately, your Heroku App is down

**Comment by ikenami** [comment]
I turned it off on accident, oops. Now it's up and running. :D

**Comment by martincarrera** [comment]
The website looks really well! I

'll add it to the list of projects, thanks for using my API 😸

**Comment by TorzuoliH** [comment]
I got these requests failing @ikenami, what's happening?

**Comment by ikenami** [comment]
Hey, @TorzuoliH , I see. The problem is that different browsers treat the Mixed Contend error differently. This happens because Heroku server the website via HTTPS and I'm making an HTTP request to the API. Chrome let it pass as a warning, that's why it worked fine for me. But other browsers (Safari, Edge, Mozilla,..) block the content instead, that's why you get these error messages.

I've made some changes on my application and it should work just fine in any browser if you use HTTP instead. :) Try using this link: http://deck-royale-ultimate.herokuapp.com

And if the error persists (or you would like to see some new features) you can create an issue on my project! (https://github.com/ikenami/Deck-Royale) Since this is an error from my application and not this API, it would be best if we could solve it there. :D

**Comment by TorzuoliH** [comment]
Ok I see, it seems to be solved on Chrome macOS. I tried on Chrome Windows 10, it wasn't working well.
Good job :)

**Pull request merged**
